version: "3.8"

services:
  postgres:
    image: postgres:15
    ports:
      - "8093:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: admin_butler
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - admin_butler_data:/var/lib/postgresql/data

  redis:
    image: redis:7.0.10
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "8094:6379"
    volumes:
      - admin_butler_redis:/data

volumes:
  admin_butler_data:
  admin_butler_redis:
